Add projects
Hexlet/ru-projects-for-contributing pull request #14
Opened 2024-11-13 12:58 UTC by Malcom1986

2024-11-13 12:58 UTC, Malcom1986 commented
@fey Коля, вот еще партия подъехала

2024-11-13 14:45 UTC, fey requested changes

2024-11-13 14:45 UTC, fey commented on projects/mattermost/README.md
> +# Mattermost
давай маттермост уберем. Они ну ру айпишники не пускают без впн.

2024-11-14 05:53 UTC, Malcom1986 commented
Готово

2024-11-14 09:21 UTC, merged